name: parse_server_sdk
description: The Dart SDK to connect to Parse Server. Build your apps faster with Parse Platform, the complete application stack.
version: 8.0.0
homepage: https://parseplatform.org
repository: https://github.com/parse-community/Parse-SDK-Flutter
issue_tracker: https://github.com/parse-community/Parse-SDK-Flutter/issues
documentation: https://docs.parseplatform.org/dart/guide

funding:
  - https://opencollective.com/parse-server
  - https://github.com/sponsors/parse-community

topics:
  - parse
  - parse-platform
  - parse-server
  - node-js
  - backend

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  # Networking
  dio: ^5.9.0
  http: ^1.5.0
  web_socket_channel: ^3.0.3

  #Database
  sembast: ^3.8.5+1
  sembast_web: ^2.4.2

  # Utils
  uuid: ^4.5.1
  meta: ^1.16.0
  path: ^1.9.1
  mime: ^2.0.0
  timezone: ^0.10.1
  universal_io: ^2.2.2
  xxtea: ^2.1.0
  collection: ^1.19.1
  cross_file: ^0.3.4+2

dev_dependencies:
  lints: ^6.0.0

  # Testing
  build_runner: ^2.9.0
  mockito: ^5.5.1
  test: ^1.26.3

screenshots:
  - description: Parse Platform logo.
    path: screenshots/logo.png